site_name: ZJU SIS resource sharing

theme:
  name: material
  favicon: img/favicon.png
  logo: img/favicon.png

nav: 
- Start: index.md
- 专业必修课:
  - 美国文学史: 专业必修课/American Literature.md
- 专业选修课:
  - 英语文体学: 专业选修课/English Stylistics.md
  
